# Generated by Django 5.1.1 on 2024-10-10 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondleg_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendedRestaurant',
            new_name='RecommendedShoe',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='advertisement',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='composites',
            new_name='components',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='instructions',
            new_name='contacts',
        ),
        migrations.RenameField(
            model_name='recommendedshoe',
            old_name='restaurant_url',
            new_name='shoe_url',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
