# Generated by Django 5.1.1 on 2024-10-10 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondleg_app', '0002_rename_recommendedrestaurant_recommendedshoe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='brand',
            field=models.CharField(default='Unknown Brand', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='Non image', upload_to='advertisements/'),
            preserve_default=False,
        ),
    ]
