# Generated by Django 5.1.1 on 2024-10-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondleg_app', '0003_alter_advertisement_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='components',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='contacts',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='contact_name',
            field=models.CharField(default='Contact Name Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
